baseURL: "http://localhost:1313/"
title: Daniel Roberto Palomo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: manuscripts
      name: Manuscripts
      url: /manuscripts/
      weight: 2
    - identifier: posters
      name: Posters & Abstracts
      url: /posters/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 4


params:
    description: "Daniel Palomo's portfolio website"
    author: Daniel Roberto Palomo
    DateFormat: "June 2026"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["manuscripts", "posters", "projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          disableHeaderMenu: false 
          title: Daniel Roberto Palomo
          subtitle: "I am Daniel Palomo, an undergraduate researcher at Washington University in St. Louis. I am majoring in Biomedical Engineering, and am interested in how ML can be utilized within imaging technologies for analysis."
          imageUrl: "DanielPalomo_Headshot.jpg"
          imageWidth: 160
          imageHeight: 160
          

    socialIcons:
        - name: CV
          url: Palomo_Daniel_CV.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/daniel-r-palomo/   
        - name: Email
          url: mailto:d.palomo@wustl.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=q6IhUbcAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/daniel-palomo


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Daniel Palomo"
      #icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2